array_width = 200
attr_fn_like_width = 148
chain_width = 150
comment_width = 150
fn_params_layout = "Compressed"
#fn_args_layout = "Compressed"
fn_call_width = 148
imports_indent = "Visual"
imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
trailing_comma = "Never"
max_width = 150
merge_derives = true
imports_granularity = "Module"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
remove_nested_parens = true
group_imports = "StdExternalCrate"
space_before_colon = false
space_after_colon = true
trailing_semicolon = true
wrap_comments = true